// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LegacyAppPathString } from "../LegacyAppPathString";

export type EnvironmentTransportParams = { "type": "websocket", execServerUrl: string,
/**
 * Optional WebSocket connection timeout. The server default applies when omitted.
 */
connectTimeoutMs?: number | null, } | { "type": "stdio", program: string, args?: Array<string> | null, env?: { [key in string]?: string } | null, cwd?: LegacyAppPathString | null,
/**
 * Optional stdio initialize timeout. The server default applies when omitted.
 */
initializeTimeoutMs?: number | null, };
